apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-springboot-app
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:guest
